# Basic info
title: Jabran Rafique
tagline: 'web developer, cartographer'
description: 'I develop ideas that are useful and beneficial to everyone. I am a web developer based in England, UK'
version: 0.0.2

# Routes
baseurl: /
# url: http://127.0.0.1:4000
url: http://jabranr.github.io
avatar: https://graph.facebook.com/jabranr/picture?size=large
permalink: /:categories/:title/

# Pagination
paginate: 10

# Dependencies
markdown: redcarpet
pygments: true
